version: "3.8"

services:
  backend:
    build: ./backend
    container_name: online-cinema-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=onlinecinemadb
      - JWT_SECRET=test
      - JWT_EXPIRATION=3600s
      - JWT_REFRESH_SECRET=test2
      - JWT_REFRESH_EXPIRATION=3600s
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - online-cinema-net
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: online-cinema-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - online-cinema-net
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_SERVER_HOST=true

  db:
    image: postgres:15
    container_name: online-cinema-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onlinecinemadb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - online-cinema-net

  redis:
    image: redis:latest
    container_name: online-cinema-redis
    command: ["redis-server", "--appendonly", "yes"] # Enable data persistence
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data # Persist data
    networks:
      - online-cinema-net

volumes:
  postgres_data:
  redis_data:

networks:
  online-cinema-net:
    driver: bridge
